import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from './auth.routes.js';
import usersRoutes from './users.routes.js';
import branchRoutes from './branch.routes.js';
import categoryRoutes from './category.routes.js';
import uploadRoutes from './upload.routes.js';
import productRoutes from './product.routes.js';
import qrRoutes from './qr.routes.js';
import qrCatalogRoutes from './qrCatalog.routes.js';
import customerRoutes from './customer.routes.js';
import rentalRoutes from './rental.routes.js';
import comboRoutes from './combo.routes.js';
import transferRoutes from './transfer.routes.js';
import notificationRoutes from './notification.routes.js';
import auditRoutes from './audit.routes.js';
import maintenanceRoutes from './maintenance.routes.js';
import invoiceRoutes from './invoice.routes.js';
import paymentRoutes from './payment.routes.js';
import shiftRoutes from './shift.routes.js';
import reportRoutes from './report.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import settingsRoutes from './settings.routes.js';
import teamRoutes from './team.routes.js';
import leaveRoutes from './leave.routes.js';
import attendanceSelfRoutes from './attendance.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/branches', branchRoutes);
router.use('/categories', categoryRoutes);
router.use('/uploads', uploadRoutes);
router.use('/products', productRoutes);
router.use('/qr', qrRoutes);
router.use('/qr-catalog', qrCatalogRoutes);
router.use('/customers', customerRoutes);
router.use('/rentals', rentalRoutes);
router.use('/combos', comboRoutes);
router.use('/transfers', transferRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/payments', paymentRoutes);
router.use('/shifts', shiftRoutes);
router.use('/reports', reportRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/team', teamRoutes);
router.use('/leaves', leaveRoutes);
router.use('/attendance', attendanceSelfRoutes);

export default router;
