import { RENTAL_STATUS, RENTAL_ITEM_STATUS } from '../models/constants/enums.js';
import AppError from './AppError.js';

/** Statuses that hold inventory / block overlapping bookings */
export const RENTAL_BLOCKING_STATUSES = [
  RENTAL_STATUS.RESERVED,
  RENTAL_STATUS.CONFIRMED,
  RENTAL_STATUS.PICKED_UP,
  RENTAL_STATUS.ACTIVE,
  RENTAL_STATUS.OVERDUE,
  RENTAL_STATUS.MAINTENANCE,
  RENTAL_STATUS.PARTIALLY_RETURNED,
];

/** Item statuses that count as holding a unit */
export const RENTAL_ITEM_BLOCKING_STATUSES = [
  RENTAL_ITEM_STATUS.RESERVED,
  RENTAL_ITEM_STATUS.ISSUED,
];

export const DEFAULT_RESERVATION_TTL_MINUTES = 30;

export const RENTAL_STATUS_TRANSITIONS = {
  [RENTAL_STATUS.DRAFT]: [RENTAL_STATUS.RESERVED, RENTAL_STATUS.CANCELLED],
  [RENTAL_STATUS.RESERVED]: [
    RENTAL_STATUS.CONFIRMED,
    RENTAL_STATUS.PICKED_UP,
    RENTAL_STATUS.ACTIVE,
    RENTAL_STATUS.CANCELLED,
  ],
  [RENTAL_STATUS.CONFIRMED]: [
    RENTAL_STATUS.PICKED_UP,
    RENTAL_STATUS.CANCELLED,
  ],
  [RENTAL_STATUS.PICKED_UP]: [
    RENTAL_STATUS.ACTIVE,
    RENTAL_STATUS.RETURNED,
    RENTAL_STATUS.PARTIALLY_RETURNED,
    RENTAL_STATUS.MAINTENANCE,
    RENTAL_STATUS.CANCELLED,
  ],
  [RENTAL_STATUS.ACTIVE]: [
    RENTAL_STATUS.OVERDUE,
    RENTAL_STATUS.RETURNED,
    RENTAL_STATUS.PARTIALLY_RETURNED,
    RENTAL_STATUS.MAINTENANCE,
  ],
  [RENTAL_STATUS.OVERDUE]: [
    RENTAL_STATUS.RETURNED,
    RENTAL_STATUS.PARTIALLY_RETURNED,
    RENTAL_STATUS.MAINTENANCE,
  ],
  [RENTAL_STATUS.PARTIALLY_RETURNED]: [
    RENTAL_STATUS.RETURNED,
    RENTAL_STATUS.MAINTENANCE,
  ],
  [RENTAL_STATUS.MAINTENANCE]: [
    RENTAL_STATUS.ACTIVE,
    RENTAL_STATUS.OVERDUE,
    RENTAL_STATUS.RETURNED,
    RENTAL_STATUS.PARTIALLY_RETURNED,
  ],
  [RENTAL_STATUS.RETURNED]: [RENTAL_STATUS.CLOSED],
  [RENTAL_STATUS.CANCELLED]: [],
  [RENTAL_STATUS.CLOSED]: [],
};

export const assertRentalTransition = (from, to) => {
  const allowed = RENTAL_STATUS_TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    throw new AppError(`Cannot transition rental from ${from} to ${to}`, 400);
  }
};
